# Sentiment Analysis Configuration

# Data Processing 
data:
  raw_data_path: data/raw/
  processed_data_path: data/processed/
  max_sequence_length: 100
  text_column: text

# Model Configuration
model:
  model_path: models/rf_basic.pkl
  word2vec:
    model_path: models/model_wv.bin
    vector_size: 100
    window: 5
    min_count: 1
    embedding_dim: 100

# API Configuration
api:
  host: 0.0.0.0
  port: 8786
  debug: false

# Logging Configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/sentiment_analysis.log

# Training Configuration
training:
  train_size: 0.8
  test_size: 0.1
  val_size: 0.1
  random_state: 42 